/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.d0tplist.netwhatsapp;

import com.sun.javafx.PlatformUtil;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebErrorEvent;
import javafx.scene.web.WebView;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.d0tplist.netwhatsapp//WhatsAppView//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "WhatsAppViewTopComponent",
        iconBase = "org/d0tplist/netwhatsapp/whatsapp16.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = false)
@ActionID(category = "Window", id = "org.d0tplist.netwhatsapp.WhatsAppViewTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_WhatsAppViewAction",
        preferredID = "WhatsAppViewTopComponent"
)
@Messages({
    "CTL_WhatsAppViewAction=WhatsAppView",
    "CTL_WhatsAppViewTopComponent=WhatsAppView",
    "HINT_WhatsAppViewTopComponent=This is a WhatsAppView"
})
public final class WhatsAppViewTopComponent extends TopComponent {

    public Aux aux;

    public WhatsAppViewTopComponent() {
        initComponents();
        setName(Bundle.CTL_WhatsAppViewTopComponent());
        setToolTipText(Bundle.HINT_WhatsAppViewTopComponent());

        if (PlatformUtil.isWindows()) {
            if (!PlatformUtil.isWinVistaOrLater()) {
                super.add(new JLabel("Sorry, your windows is more older than my granpa :("));
                return;
            }
        }

        aux = new Aux();
        aux.getButtonLoad().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                init();
            }
        });

        super.add(aux);

    }

    public void init() {
        removeAll();
        Browser browser = new Browser();
        BrowserView view = new BrowserView(browser);
        add(view);
        browser.setUserAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 OPR/50.0.2762.67");
        browser.loadURL("https://web.whatsapp.com");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
